name: build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Library
        run: |
          cd library
          mvn --batch-mode --update-snapshots verify install

      - name: Build AWS-S3
        run: |
          cd springboot-aws-s3
          mvn --batch-mode --update-snapshots verify

      - name: Build AWS-S3QS
        run: |
          cd springboot-aws-sqs
          mvn --batch-mode --update-snapshots verify

